"""add user tbl

Revision ID: 3cf073d02320
Revises: a6b8984c9ee6
Create Date: 2023-07-20 21:16:39.890398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf073d02320'
down_revision = 'a6b8984c9ee6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
